# Generated by Django 6.0.5 on 2026-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bc', models.CharField(max_length=20, unique=True, verbose_name='Código Dynamics/BC')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('cif_nif', models.CharField(blank=True, max_length=20, verbose_name='CIF o NIF')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección Postal')),
                ('tarifa_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tarifa (€/kg)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Cliente en Activo?')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Nuestros Clientes',
            },
        ),
    ]
