# Generated by Django 6.0.5 on 2026-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='alias',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='centro_responsabilidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Centro responsabilidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cod_almacen',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cód. almacén'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Departamento Code'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='programa_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Programa Code'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='programa_filter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Programa Filter'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_periodo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo periodo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿En Activo?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cif_nif',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIF/NIF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_bc',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nº (Código)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
